### ISSUE TITLE
Hide OPT_SKIDBUFFER Declaration Unless FORMAL is Defined

### ISSUE THREAD

**Issue by bobnewgard** [ZipCPU/axidmacheck#2]
Verilator v4.212 (and v4.202) fails with unconnected OPT_SKIDBUFFER
when FORMAL is undefined. I fixed this and pushed the change to
https://github.com/bobnewgard/axidmacheck (see Details below).  The
diff is:

    --- a/rtl/streamcounter.v
    +++ b/rtl/streamcounter.v
    @@ -58,7 +58,9 @@ module        streamcounter #(
                    parameter       C_AXI_ADDR_WIDTH = 4,
                    localparam      C_AXI_DATA_WIDTH = 32,
                    parameter       C_AXIS_DATA_WIDTH = 32,
    +`ifdef FORMAL
                    parameter [0:0] OPT_SKIDBUFFER = 1'b1,
    +`endif
                    parameter [0:0] OPT_LOWPOWER = 0,
                    localparam      ADDRLSB = $clog2(C_AXI_DATA_WIDTH)-3
                    // }}}

Regards,
Bob Newgard

Details:
* https://github.com/ZipCPU/autofpga/commit/f89d4dce81baed312c843c8554923fee7750d0a1
* https://github.com/bobnewgard/axidmacheck/commit/af7511a857310634db00f5a0e10a19abd159be3e
* Verilator v4.212

**Comment by ZipCPU** [comment]
Thank you.  Let me double check this, but I seem to recall this is a necessary update.

**Comment by ZipCPU** [comment]
Ahh, yes, the skidbuffer was _supposed_ to have initial statements, but only when built in an FPGA environment.  The `OPT_INITIAL` flag was supposed to determine if they were used or not.  However, when building in an ASIC environment the two configurations appear to have been confused.  Perhaps the "right" answer is to put the initial statements back in.  They'd read like:

   initial if (OPT_INITIAL) regval = 0;

or some such.

Dan

**Comment by ZipCPU** [comment]
Ok, I looked into this.  OPT_SKIDBUFFER is a relic of an older design that's now being outlined by the newer Verilator.  It needs to be removed entirely.  The FORMAL section also needs to be adjusted under the assumption that OPT_SKIDBUFFER is true since the skid buffers are being used.

There are more changes required to work with the newer Verilator, those'll be posted soon as well.

However, before fixing this ... I need to fix the DMA.  The CSYS* parameters were just a pain, the documentation was never quite right for them, etc.  So, I'm likely to remove them entirely, but I'll still need to test the replacement before posting it.

**Comment by ZipCPU** [comment]
This and the AXIDMA issue have now been fixed as of [d65b46a](https://github.com/ZipCPU/axidmacheck/commit/d65b46a86bf9cf71755c0128a31ae3efd47c0404).

Dan
